#pragma once
#include <typeinfo> //Required by some compilers
#include <Standard/String.h>
#include <Standard/List.h>
#include "Utils/Console.h"
#include "Utils/StringHelper.h"

namespace Tristeon
{
	/**
	 * A cross-compiler/platform class for generating consistent type data.
	 */
	template <typename T>
	struct Type
	{
		/**
		 * Get the type's full name, including its namespace.
		 */
		static String fullName();
	};


#ifdef _MSC_VER
	template <typename T>
	String Type<T>::fullName()
	{
		//MSVC generates "typename <Class>". Remove the typename bit.
		const String name = typeid(T).name();
		List<String> vec = StringHelper::split(name, ' ');
		if (vec.size() < 2)
		{
			Console::warning("Type failed to interpret the MSVC typename. Returning direct typeid(T).name(): " + String(typeid(T).name()));
			return name;
		}

		String result;
		for (auto i = 1; i < vec.size(); i++)
		{
			result += vec[i];
		}
		return result;
	}
#else
#include <cxxabi.h>

	template <typename T>
	String Type<T>::fullName()
	{
		//Demangle the typename generated by GCC
		int status;
		char* realName = abi::__cxa_demangle(typeid(T).name(), 0, 0, &status);
		String result = { realName };
		free(realName);
		return result;
	}
#endif
}
